```yaml
project:
  type: book
  output-dir: docs

book:
  title: "您的書名"
  author: "您的名字"
  date: "最後更新日期"
  chapters:
    - index.qmd
    - intro.qmd
    - chapter1.qmd
    - chapter2.qmd
    - references.qmd

format:
  html:
    theme: cosmo
    css: styles.css
  pdf:
    documentclass: scrreprt

execute:
  freeze: auto

bibliography: references.bib

language:
  ui:
    chapter_name: "章節 "

resources:
  - CNAME
```
